kitchen_services/urls.py
from django.urls import path, include
from kitchen_services.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen_services"

restaurant/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen_services.urls", namespace="kitchen_services")),
    path("", include("django.contrib.auth.urls")),
] # + debug_toolbar_urls()

templates/includes/footer-components.html
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a>
              coded by AppSeed.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              &copy; created by Andrii Fedchuk
            </p>
          </div>
        </div>
  </footer>

templates/includes/navigation-light.html
  <!-- Navbar Light -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    <div class="container">
      <a class="navbar-brand" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
        Home
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
            <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages5" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
              Pages
              <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
            </a>
            <div class="dropdown-menu ms-n3 dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages5">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Kitchen service
                      </h6>
                      <a href="{% url 'kitchen_services:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Cook List</span>
                      </a>
                      <a href="{% url 'kitchen_services:dish-type-list' %}" class="dropdown-item border-radius-md">
                        <span>Dish Type list</span>
                      </a>
                      <a href="{% url 'kitchen_services:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Dish List</span>
                      </a>
                    </div>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="https://github.com/AndriiFn/restaurant-kitchen-service"
                     target="_blank" class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">PROJECT ON GITHUB</a>
                </li>

                  {% if request.user.is_authenticated %}
                    <li class="nav-item ms-lg-auto">
                      <form method="post" action="{% url 'logout' %}" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="border-0 bg-transparent text-danger fw-medium" style="cursor: pointer;">
                          Logout
                        </button>
                      </form>
                    </li>
                  {% endif %}

                
        </ul>
      </div>
    </div>
  </nav>

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Home
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Pages
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Kitchen service
                      </h6>
                      <a href="{% url 'kitchen_services:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Cook List</span>
                      </a>
                      <a href="{% url 'kitchen_services:dish-type-list' %}" class="dropdown-item border-radius-md">
                        <span>Dish Type list</span>
                      </a>
                      <a href="{% url 'kitchen_services:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Dish List</span>
                      </a>
                    </div>
                  </div>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="https://github.com/AndriiFn/restaurant-kitchen-service"
                     target="_blank" class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">PROJECT ON GITHUB</a>
                </li>

                {% if request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <form method="post" action="{% url 'logout' %}" class="d-inline">
                      {% csrf_token %}
                      <button type="submit" class="border-0 bg-transparent text-danger fw-medium" style="cursor: pointer;">
                        Logout
                      </button>
                    </form>
                  </li>
                {% endif %}




              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <section class="py-7">
    <div class="container">
      <div class="row justify-content-center py-2">
        <div class="col-lg-4 mx-auto">
          <ul class="pagination pagination-primary justify-content-center m-4">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link rounded-circle" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
                  <i class="material-icons" aria-hidden="true">←</i>
                </a>
              </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="javascript:;">
                {{ page_obj.number }} of {{ paginator.num_pages }}
              </a>
            </li>

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link rounded-circle" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
                  <i class="material-icons" aria-hidden="true">→</i>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/sidebar.html
{#<ul class="sidebar-nav list-group">#}
{#  {% if user.is_authenticated %}#}
{#    <li class="list-group-item">#}
{#      User: {{ user.username }}#}
{#    </li>#}
{#    <form method="post" action="{% url 'logout' %}">#}
{#      {% csrf_token %}#}
{#      <button class="btn btn-outline-dark" type="submit" >Log out</button>#}
{#    </form>#}
{#  {% else %}#}
{#    <li class="list-group-item">#}
{#      <a href="{% url 'login' %}">Login</a>#}
{#    </li>#}
{#  {% endif %}#}
{#  <br>#}
{##}
{#  <li class="list-group-item">#}
{#    <a href="{% url 'kitchen_services:index' %}">Home page</a>#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url 'kitchen_services:dish-list' %}">All dishes</a>#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url 'kitchen_services:dish-type-list' %}">All types of dishes</a>#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url 'kitchen_services:cook-list' %}">All cooks</a>#}
{#  </li>#}
{#</ul>#}