kitchen_services/urls.py
from django.urls import path, include
from kitchen_services.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen_services"

restaurant/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen_services.urls", namespace="kitchen_services")),
    path("", include("django.contrib.auth.urls")),
] # + debug_toolbar_urls()

kitchen_services/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "Dish type"
        verbose_name_plural = "Dish types"
        ordering = ("name", )

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.PositiveIntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(45)]
    )

    class Meta:
        ordering = ("-years_of_experience", )

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        validators=[MinValueValidator(0.01), MaxValueValidator(1000)]
    )
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="cooked_dishes")

    class Meta:
        verbose_name_plural = "Dishes"
        ordering = ("price", )

    def __str__(self):
        return self.name

kitchen_services/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen_services.models import Cook, Dish, DishType


class CookCreationForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "years_of_experience", )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.exclude(is_superuser=True),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeForm(forms.ModelForm):
    dishes = forms.ModelMultipleChoiceField(
        queryset=Dish.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = DishType
        fields = "__all__"


class DishTypeCreationForm(forms.ModelForm):
    dishes = forms.ModelMultipleChoiceField(
        queryset=Dish.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = DishType
        fields = "__all__"


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish name",
            }
        )
    )


class CookSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by a cook's last name",
            }
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish type name",
            }
        )
    )

kitchen_services/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen_services.models import DishType, Cook, Dish
from kitchen_services.forms import (
    CookCreationForm,
    DishForm,
    DishSearchForm,
    DishTypeSearchForm,
    CookSearchForm,
    DishTypeCreationForm,
    DishTypeForm,
)


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_dish_types = DishType.objects.count()
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_dish_types": num_dish_types,
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_visits": num_visits + 1,
    }

    return render(request, "kitchen_services/index.html", context=context)


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.select_related("dish_type")
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["name"] = name
        context["search_form"] = DishSearchForm(
            initial={"name": name},
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    queryset = Dish.objects.select_related("dish_type").prefetch_related("cooks")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen_services:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen_services:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen_services:dish-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen_services/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["name"] = name
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name},
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeCreationForm
    success_url = reverse_lazy("kitchen_services:dish-type-list")
    template_name = "kitchen_services/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    form_class = DishTypeForm
    success_url = reverse_lazy("kitchen_services:dish-type-list")
    template_name = "kitchen_services/dish_type_form.html"
    context_object_name = "dish_type"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen_services:dish-type-list")
    template_name = "kitchen_services/dish_type_confirm_delete.html"
    context_object_name = "dish_type"


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        last_name = self.request.GET.get("last_name", "")
        context["last_name"] = last_name
        context["search_form"] = CookSearchForm(
            initial={"last_name": last_name},
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(last_name__icontains=form.cleaned_data["last_name"])
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("cooked_dishes")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen_services:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen_services:cook-list")

templates/kitchen_services/cook_confirm_delete.html
{% extends "layouts/base.html" %}

{% block title %} Cook Delete {% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Delete Cook</h1>
    </div>

    <h4>Are you sure you want to delete the cook <strong>"{{ cook.username }}"</strong>?</h4>
    <p class="text-muted">This action is permanent and cannot be undone. All the associated data for this cook will be deleted.</p>

    <div class="d-flex justify-content-between">
      <a href="{% url 'kitchen_services:cook-list' %}" class="btn btn-outline-secondary btn-lg w-48">Cancel</a>

      <form action="" method="post" class="w-48">
        {% csrf_token %}
        <input type="submit" value="Yes, delete the cook" class="btn btn-danger btn-lg w-100">
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/cook_detail.html
{% extends "layouts/base.html" %}

{% block title %} Cook Detail {% endblock %}

{% block content %}
  <div class="container mt-5">
    <!-- Title and Update Button -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="display-4">Cook {{ cook.username }} Details</h1>
    </div>

    <!-- Cook Details -->
    <div class="card mb-4 p-4">
      <h3><strong>Full Name:</strong> {{ cook.first_name }} {{ cook.last_name }}</h3>
      <h4><strong>Years of Experience:</strong>
        {% if not cook.years_of_experience %}
          Beginner cook
        {% else %}
          {{ cook.years_of_experience }} year{{ cook.years_of_experience|pluralize }} -
          {% if cook.years_of_experience >= 10 %} Highly experienced cook
          {% elif cook.years_of_experience >= 5 %} Skilled cook
          {% elif cook.years_of_experience >= 0 %} Beginner cook {% endif %}
        {% endif %}
      </h4>
    </div>

    <!-- Cook's Dishes -->
    {% if cook.cooked_dishes.count == 0 %}
      <h5>This cook can't cook anything yet, but they're learning!</h5>
    {% else %}
      <p><strong>Number of dishes this cook can prepare:</strong> {{ cook.cooked_dishes.count }}</p>
      <h3 class="mt-4">Dishes:</h3>
      <ul class="list-group">
        {% for dish in cook.cooked_dishes.all %}
          <li class="list-group-item">
            <a href="{% url 'kitchen_services:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
          </li>
        {% endfor %}
      </ul>
    {% endif %}

    <!-- Delete Button -->
    <div class="mt-4">
      <a href="{% url 'kitchen_services:cook-delete' pk=cook.id %}" class="btn btn-danger btn-lg">Delete</a>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/cook_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Cook Create {% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="display-4">Create Cook</h1>
    </div>

    <div class="card p-4 shadow-sm">
      <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group mb-3">
          {{ form|crispy }}
        </div>

        <div class="form-group d-flex justify-content-between">
          <a href="{% url 'kitchen_services:cook-list' %}" class="btn btn-outline-secondary btn-lg w-48">Cancel</a>
          <input type="submit" value="Submit" class="btn btn-primary btn-lg w-48">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/cook_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Cook List {% endblock %}

{% block content %}
  <div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Our Cooks</h1>
      <a href="{% url 'kitchen_services:cook-create' %}" class="btn btn-primary btn-sm">+ Add Cook</a>
    </div>

    <form method="get" action="" >
      <div >
        {{ search_form|crispy }}
        <button type="submit" class="btn btn-outline-secondary">
          <i class="fas fa-search"></i> 🔍
        </button>
      </div>
    </form>

    {% if not cook_list %}
      <div>There are no cooks available, unfortunately :(</div>
    {% else %}
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Full Name</th>
              <th>Username</th>
              <th>Years of Experience</th>
            </tr>
          </thead>
          <tbody>
            {% for cook in cook_list %}
              {% if not cook.is_superuser %}
              <tr>
                <td><a style="color: blue" href="{% url 'kitchen_services:cook-detail' pk=cook.id %}">{{ cook.id }}</a></td>
                <td>{{ cook.first_name }} {{ cook.last_name }}</td>
                <td>{{ cook.username }}</td>
                <td>{{ cook.years_of_experience|default:"0" }} year{{ cook.years_of_experience|pluralize }} of experience</td>
              </tr>
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
  </div>

  {% include 'includes/pagination.html' %}
{% endblock %}

templates/kitchen_services/dish_confirm_delete.html
{% extends "layouts/base.html" %}

{% block title %} Dish Delete {% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Delete Dish</h1>
    </div>

    <h4>Are you sure you want to delete the dish <strong>"{{ dish.name }}"</strong>?</h4>
    <p class="text-muted">This action is permanent and cannot be undone. The dish will be permanently deleted from the system.</p>

    <div class="d-flex justify-content-between">

      <a href="{% url 'kitchen_services:dish-list' %}" class="btn btn-outline-secondary btn-lg w-48">Cancel</a>

      <form action="" method="post" class="w-48">
        {% csrf_token %}
        <input type="submit" value="Yes, delete it" class="btn btn-danger btn-lg w-100">
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/dish_detail.html
{% extends "layouts/base.html" %}

{% block title %} Dish Detail {% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="display-4">{{ dish.name }} Details</h1>
      <a href="{% url 'kitchen_services:dish-update' pk=dish.id %}" class="btn btn-secondary">Update</a>
    </div>

    <div class="card mb-4 p-4">
      <h3><strong>Price:</strong> ${{ dish.price }}</h3>
      <h4><strong>Dish Type:</strong> {{ dish.dish_type }}</h4>
      <p class="lead">{{ dish.description }}</p>
    </div>

    <h3 class="mt-4 mb-3">Cook{{ dish.cooks.all.count|pluralize }}:</h3>
    <div class="list-group">
      {% for cook in dish.cooks.all %}
        <div class="list-group-item">
          <h5>{{ cook.first_name }} {{ cook.last_name }}</h5>
          <p>
            {% if cook.years_of_experience >= 1 %}
              with {{ cook.years_of_experience|default:"0" }} year{{ cook.years_of_experience|pluralize }} of experience
            {% elif cook.years_of_experience == 0 %}
              <em>- still mastering the basics, but the future looks delicious!</em>
            {% endif %}
          </p>
        </div>
      {% endfor %}
    </div>

    <div class="mt-4">
      <a href="{% url 'kitchen_services:dish-delete' pk=dish.id %}" class="btn btn-danger btn-lg">Delete</a>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/dish_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %}Dish {{ object|yesno:"Update, Create" }}{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="display-4">{{ object|yesno:"Update, Create" }} Dish</h1>
    </div>

    <div class="card p-4 shadow-sm">
      <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group mb-3">
          {{ form|crispy }}
        </div>
        <div class="form-group d-flex justify-content-between">
          <a href="{% url 'kitchen_services:dish-list' %}" class="btn btn-outline-secondary btn-lg w-48">Cancel</a>

          <input type="submit" value="Submit" class="btn btn-primary btn-lg w-48">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/dish_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Dish List {% endblock %}

{% block content %}
  <div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Dishes</h1>
      <a href="{% url 'kitchen_services:dish-create' %}" class="btn btn-primary btn-sm">+ Add Dish</a>
    </div>

    <form method="get" action="" class="form-inline mb-4">
      <div class="input-group">
        {{ search_form|crispy }}
        <button type="submit" class="btn btn-outline-secondary">
          <i class="fas fa-search"></i> 🔍
        </button>
      </div>
    </form>

    {% if not dish_list %}
      <div>There are no dishes available, unfortunately :(</div>
    {% else %}
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Dish Name</th>
              <th>Dish Type</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            {% for dish in dish_list %}
              <tr>
                <td><a style="color: blue" href="{% url 'kitchen_services:dish-detail' pk=dish.id %}">{{ dish.id }}</a></td>
                <td>{{ dish.name }}</td>
                <td>{{ dish.dish_type }}</td>
                <td>${{ dish.price }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
  </div>
  {% include 'includes/pagination.html' %}
{% endblock %}


templates/kitchen_services/dish_type_confirm_delete.html
{% extends "layouts/base.html" %}

{% block title %}Dish Type Delete {% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Delete Dish Type</h1>
    </div>

    <h4>Are you sure you want to delete the dish type <strong>"{{ dish_type.name }}"</strong>?</h4>
    <p class="text-muted">This action is permanent and cannot be undone. All dishes related to this dish type will also be deleted.</p>

    <div class="d-flex justify-content-between">
      <a href="{% url 'kitchen_services:dish-type-list' %}" class="btn btn-outline-secondary btn-lg w-48">Cancel</a>

      <form action="" method="post" class="w-48">
        {% csrf_token %}
        <input type="submit" value="Yes, delete it" class="btn btn-danger btn-lg w-100">
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/dish_type_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %}Dish Type {{ object|yesno:"Update, Create" }}{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="display-4">{{ object|yesno:"Update, Create" }} Dish Type</h1>
    </div>

    <div class="card p-4 shadow-sm">
      <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group mb-3">
          {{ form|crispy }}
        </div>
        <div class="form-group d-flex justify-content-between">
          <!-- Cancel Button -->
          <a href="{% url 'kitchen_services:dish-type-list' %}" class="btn btn-outline-secondary btn-lg w-48">Cancel</a>

          <!-- Submit Button -->
          <input type="submit" value="Submit" class="btn btn-primary btn-lg w-48">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen_services/dish_type_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Dish Type Delete {% endblock %}

{% block content %}
  <div class="container mt-4">
    <!-- Title and Add Button -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Dish Types</h1>
      <a href="{% url 'kitchen_services:dish-type-create' %}" class="btn btn-primary btn-sm">+ Add Dish Type</a>
    </div>

    <!-- Search Form -->
    <form method="get" action="" >
      <div >
        {{ search_form|crispy }}
        <button type="submit" class="btn btn-outline-secondary">
          <i class="fas fa-search"></i> 🔍
        </button>
      </div>
    </form>

    <!-- Dish Types List -->
    {% if not dish_type_list %}
      <div>There are unfortunately no dish types available :(</div>
    {% else %}
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Dish Type Name</th>
              <th>Number of Dishes</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for dish_type in dish_type_list %}
              <tr>
                <td>{{ dish_type.id }}</td>
                <td>{{ dish_type.name }}</td>
                <td>{{ dish_type.dishes.all.count }}</td>
                <td>
                  <a href="{% url 'kitchen_services:dish-type-update' pk=dish_type.id %}" class="btn btn-danger btn-sm">Update</a>
                </td>
                <td>
                  <a href="{% url 'kitchen_services:dish-type-delete' pk=dish_type.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
  </div>

  {% include 'includes/pagination.html' %}
{% endblock %}